### ISSUE TITLE
How to use this repo?

### ISSUE THREAD

**Issue by thiagowfx** [fukawi2/aur4-pkgs#1]
Hey there!

Is this intended to be just a personal repo or did you create it so anyone could use it?

It looks useful but I'm slightly confused about how I'm supposed to use it. Would you be willing to write a small tutorial for it?

I personally have a [PKGBUILDs](https://github.com/thiagowfx/PKGBUILDs) repo for AUR 3.x and I'm looking for a way to manage/update it for AUR4.

Thanks in advance!

**Comment by fukawi2** [comment]
These scripts are from @eli-schwartz so you'd be better off having a look at their repo: https://github.com/eli-schwartz/pkgbuilds/

**Comment by thiagowfx** [comment]
Okay, thanks.
